# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['minecraft_server_wrapper.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('server_config.json', '.'),
        ('minecraft_background.svg', '.'),
        ('README.md', '.'),
        ('server_files', 'server_files'),
    ],
    hiddenimports=[
        'flask',
        'flask_socketio',
        'psutil',
        'threading',
        'subprocess',
        'json',
        'os',
        'time',
        'datetime',
        'logging',
        'signal',
        'sys',
        'webbrowser',
        'socketio',
        'engineio',
        'werkzeug',
        'werkzeug.serving',
        'werkzeug.utils',
        'jinja2',
        'markupsafe',
        'itsdangerous',
        'click',
        'blinker',
        'eventlet',
        'eventlet.wsgi',
        'eventlet.green',
        'greenlet',
        'dns',
        'dns.resolver',
        'six',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.ttk',
        'tkinter.scrolledtext',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MinecraftServerWrapper',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    cofile=None,
    icon=None,
)